import { useState, useEffect, useRef } from "react";
import { reportService } from "../services/reportService";
import { supabase } from "../../../core/data/remote/supabase";

export const useMaintenanceReport = (propertyId, limit = 12, autoGenerate = true) => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const hasAutoGenerated = useRef(false);

  const fetchData = async () => {
    try {
      setLoading(true);
      setError(null);

      const summaryData = await reportService.getMaintenanceSummary(
        propertyId,
        limit
      );

      // Nếu chưa có dữ liệu và cho phép auto-generate, tự động tạo báo cáo
      if ((!summaryData || summaryData.length === 0) && autoGenerate && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        
        try {
          const today = new Date();
          const startDate = new Date(today.getFullYear(), today.getMonth(), 1)
            .toISOString()
            .split("T")[0];
          const endDate = today.toISOString().split("T")[0];
          
          await reportService.generateMaintenanceReport(
            propertyId,
            startDate,
            endDate
          );
          
          // Fetch lại sau khi generate
          const newData = await reportService.getMaintenanceSummary(
            propertyId,
            limit
          );
          setData(newData);
        } catch (genError) {
          console.error("Auto-generate maintenance report failed:", genError);
          setData([]);
        }
      } else {
        setData(summaryData);
      }
    } catch (err) {
      console.error("Error fetching maintenance report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!propertyId) {
      setLoading(false);
      return;
    }

    fetchData();
  }, [propertyId, limit, autoGenerate]);

  // 🔥 REALTIME SUBSCRIPTION - Tự động refresh khi có thay đổi
  useEffect(() => {
    if (!propertyId) return;

    let refetchTimeout;

    // Debounced refetch để tránh nhiều lần fetch liên tiếp
    const debouncedRefetch = () => {
      clearTimeout(refetchTimeout);
      refetchTimeout = setTimeout(async () => {
        // Tự động regenerate báo cáo khi có thay đổi
        try {
          const today = new Date();
          const startDate = new Date(today.getFullYear(), today.getMonth(), 1)
            .toISOString()
            .split("T")[0];
          const endDate = today.toISOString().split("T")[0];
          
          await reportService.generateMaintenanceReport(
            propertyId,
            startDate,
            endDate
          );
          
          // Fetch lại sau khi regenerate
          const updatedData = await reportService.getMaintenanceSummary(
            propertyId,
            limit
          );
          setData(updatedData);
        } catch (error) {
          console.error("Auto-regenerate maintenance report failed:", error);
          // Nếu regenerate fail, chỉ refresh data hiện có
          fetchData();
        }
      }, 2000); // Đợi 2 giây để tránh regenerate quá nhiều lần
    };

    console.log("🔔 Setting up realtime subscription for maintenance report");

    const channel = supabase
      .channel(`maintenance-report-${propertyId}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "maintenance",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance created, refreshing maintenance report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "maintenance",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance updated, refreshing maintenance report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "maintenance_requests",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance request created, refreshing maintenance report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "maintenance_requests",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance request updated, refreshing maintenance report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "maintenance_summary",
          filter: `property_id=eq.${propertyId}`,
        },
        (payload) => {
          console.log("🔔 REALTIME: New maintenance summary created");
          // Chỉ refresh data, không regenerate
          fetchData();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "maintenance_summary",
          filter: `property_id=eq.${propertyId}`,
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance summary updated");
          // Chỉ refresh data, không regenerate
          fetchData();
        }
      )
      .subscribe((status) => {
        if (status === "SUBSCRIBED") {
          console.log("✅ Maintenance report realtime connected");
        } else if (status === "CHANNEL_ERROR") {
          console.error("❌ Maintenance report realtime error");
        }
      });

    // Cleanup subscription on unmount
    return () => {
      console.log("🔴 Cleaning up maintenance report realtime subscription");
      clearTimeout(refetchTimeout);
      supabase.removeChannel(channel);
    };
  }, [propertyId]);

  const generateReport = async (startDate, endDate) => {
    try {
      setLoading(true);
      setError(null);

      await reportService.generateMaintenanceReport(
        propertyId,
        startDate,
        endDate
      );

      // Refresh data after generation
      const updatedData = await reportService.getMaintenanceSummary(
        propertyId,
        limit
      );
      setData(updatedData);

      return updatedData;
    } catch (err) {
      console.error("Error generating maintenance report:", err);
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  const refresh = async () => {
    try {
      setLoading(true);
      const updatedData = await reportService.getMaintenanceSummary(
        propertyId,
        limit
      );
      setData(updatedData);
    } catch (err) {
      console.error("Error refreshing maintenance report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return {
    data,
    loading,
    error,
    generateReport,
    refresh,
  };
};
