import { useState, useEffect, useRef, useCallback } from "react";
import { reportService } from "../services/reportService";
import { supabase } from "../../../core/data/remote/supabase";

export const useMaintenanceReport = (propertyId, periodType = "MONTHLY", limit = 12, autoGenerate = true, dateFilter = null) => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const hasAutoGenerated = useRef(false);
  const isGeneratingRef = useRef(false);
  const lastPeriodType = useRef(periodType);

  // Reset auto-generate flag when periodType changes
  useEffect(() => {
    if (lastPeriodType.current !== periodType) {
      hasAutoGenerated.current = false;
      isGeneratingRef.current = false;
      lastPeriodType.current = periodType;
    }
  }, [periodType]);

  // Memoize fetchData với useCallback
  const fetchData = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);

      const summaryData = await reportService.getMaintenanceSummary(
        propertyId,
        periodType,
        limit,
        dateFilter
      );

      // Nếu propertyId = null (tất cả properties), không cần auto-generate vì đã tính từ maintenance table trực tiếp
      // Chỉ auto-generate khi propertyId được cung cấp và chưa có dữ liệu
      if (propertyId && (!summaryData || summaryData.length === 0) && autoGenerate && !hasAutoGenerated.current && !isGeneratingRef.current) {
        isGeneratingRef.current = true;
        hasAutoGenerated.current = true;
        
        try {
          const today = new Date();
          const startDate = new Date(today.getFullYear(), today.getMonth(), 1)
            .toISOString()
            .split("T")[0];
          const endDate = today.toISOString().split("T")[0];
          
          await reportService.generateMaintenanceReport(
            propertyId,
            startDate,
            endDate
          );
          
          // Fetch lại sau khi generate
          const newData = await reportService.getMaintenanceSummary(
            propertyId,
            periodType,
            limit,
            dateFilter
          );
          setData(newData);
        } catch (genError) {
          console.error("Auto-generate maintenance report failed:", genError);
          hasAutoGenerated.current = false;
          // Set data to empty array instead of throwing error
          setData([]);
        } finally {
          isGeneratingRef.current = false;
        }
      } else {
        setData(summaryData || []);
      }
    } catch (err) {
      console.error("Error fetching maintenance report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [propertyId, periodType, limit, autoGenerate, dateFilter]);

  useEffect(() => {
    // Allow fetching when propertyId is null (all properties) or when propertyId is provided
    fetchData();
  }, [fetchData]);

  // 🔥 REALTIME SUBSCRIPTION - Tự động refresh khi có thay đổi
  useEffect(() => {
    let refetchTimeout;
    let isMounted = true; // Track mount status

    // Debounced refetch để tránh nhiều lần fetch liên tiếp
    const debouncedRefetch = () => {
      if (!isMounted) return;
      
      clearTimeout(refetchTimeout);
      refetchTimeout = setTimeout(async () => {
        if (!isMounted) return;
        
        // Tự động regenerate báo cáo khi có thay đổi (chỉ khi có propertyId)
        if (propertyId) {
          try {
            const today = new Date();
            const startDate = new Date(today.getFullYear(), today.getMonth(), 1)
              .toISOString()
              .split("T")[0];
            const endDate = today.toISOString().split("T")[0];
            
            await reportService.generateMaintenanceReport(
              propertyId,
              startDate,
              endDate
            );
            
            // Fetch lại sau khi regenerate
            const updatedData = await reportService.getMaintenanceSummary(
              propertyId,
              periodType,
              limit,
              dateFilter
            );
            if (isMounted) {
              setData(updatedData);
            }
          } catch (error) {
            console.error("Auto-regenerate maintenance report failed:", error);
            // Nếu regenerate fail, chỉ refresh data hiện có
            if (isMounted) {
              fetchData();
            }
          }
        } else {
          // For all properties, just refresh data (no regenerate needed)
          if (isMounted) {
            fetchData();
          }
        }
      }, 2000); // Đợi 2 giây để tránh regenerate quá nhiều lần
    };

    console.log("🔔 Setting up realtime subscription for maintenance report");

    const channelName = propertyId 
      ? `maintenance-report-${propertyId}`
      : `maintenance-report-all-properties`;
    
    const channel = supabase.channel(channelName);

    // Subscribe to maintenance changes with property filter
    if (propertyId) {
      channel
        .on(
          "postgres_changes",
          {
            event: "INSERT",
            schema: "public",
            table: "maintenance",
            filter: `property_id=eq.${propertyId}`,
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance created, refreshing maintenance report");
            debouncedRefetch();
          }
        )
        .on(
          "postgres_changes",
          {
            event: "UPDATE",
            schema: "public",
            table: "maintenance",
            filter: `property_id=eq.${propertyId}`,
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance updated, refreshing maintenance report");
            debouncedRefetch();
          }
        );
    } else {
      channel
        .on(
          "postgres_changes",
          {
            event: "INSERT",
            schema: "public",
            table: "maintenance",
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance created (all properties), refreshing maintenance report");
            debouncedRefetch();
          }
        )
        .on(
          "postgres_changes",
          {
            event: "UPDATE",
            schema: "public",
            table: "maintenance",
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance updated (all properties), refreshing maintenance report");
            debouncedRefetch();
          }
        );
    }

    // Subscribe to maintenance_requests changes
    // Note: maintenance_requests might not have property_id directly, listen to all
    channel
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "maintenance_requests",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance request created, refreshing maintenance report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "maintenance_requests",
        },
        (payload) => {
          console.log("🔔 REALTIME: Maintenance request updated, refreshing maintenance report");
          debouncedRefetch();
        }
      );

    // Subscribe to maintenance_summary changes
    if (propertyId) {
      channel
        .on(
          "postgres_changes",
          {
            event: "INSERT",
            schema: "public",
            table: "maintenance_summary",
            filter: `property_id=eq.${propertyId}`,
          },
          (payload) => {
            console.log("🔔 REALTIME: New maintenance summary created");
            fetchData();
          }
        )
        .on(
          "postgres_changes",
          {
            event: "UPDATE",
            schema: "public",
            table: "maintenance_summary",
            filter: `property_id=eq.${propertyId}`,
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance summary updated");
            fetchData();
          }
        );
    } else {
      channel
        .on(
          "postgres_changes",
          {
            event: "INSERT",
            schema: "public",
            table: "maintenance_summary",
          },
          (payload) => {
            console.log("🔔 REALTIME: New maintenance summary created (all properties)");
            fetchData();
          }
        )
        .on(
          "postgres_changes",
          {
            event: "UPDATE",
            schema: "public",
            table: "maintenance_summary",
          },
          (payload) => {
            console.log("🔔 REALTIME: Maintenance summary updated (all properties)");
            fetchData();
          }
        );
    }

    channel.subscribe((status) => {
      if (status === "SUBSCRIBED") {
        console.log("✅ Maintenance report realtime connected");
      } else if (status === "CHANNEL_ERROR") {
        console.error("❌ Maintenance report realtime error");
      }
    });

    // Cleanup subscription on unmount
    return () => {
      console.log("🔴 Cleaning up maintenance report realtime subscription");
      isMounted = false;
      clearTimeout(refetchTimeout);
      supabase.removeChannel(channel);
    };
  }, [propertyId, periodType, limit, fetchData, dateFilter]); // Removed propertyId check - now supports all properties

  const generateReport = async (startDate, endDate) => {
    try {
      setLoading(true);
      setError(null);

      await reportService.generateMaintenanceReport(
        propertyId,
        startDate,
        endDate
      );

      // Refresh data after generation
      const updatedData = await reportService.getMaintenanceSummary(
        propertyId,
        periodType,
        limit,
        dateFilter
      );
      setData(updatedData);

      return updatedData;
    } catch (err) {
      console.error("Error generating maintenance report:", err);
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  const refresh = async () => {
    try {
      setLoading(true);
      const updatedData = await reportService.getMaintenanceSummary(
        propertyId,
        periodType,
        limit,
        dateFilter
      );
      setData(updatedData);
    } catch (err) {
      console.error("Error refreshing maintenance report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return {
    data,
    loading,
    error,
    generateReport,
    refresh,
  };
};
