import { useState, useEffect, useRef } from "react";
import { reportService } from "../services/reportService";
import { supabase } from "../../../core/data/remote/supabase";

export const useOccupancyReport = (propertyId, limit = 30, autoGenerate = true) => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const hasAutoGenerated = useRef(false);

  const fetchData = async () => {
    try {
      setLoading(true);
      setError(null);

      const summaryData = await reportService.getOccupancySummary(
        propertyId,
        limit
      );

      // Nếu chưa có dữ liệu và cho phép auto-generate, tự động tạo báo cáo
      if ((!summaryData || summaryData.length === 0) && autoGenerate && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        
        try {
          const today = new Date().toISOString().split("T")[0];
          await reportService.generateOccupancyReport(propertyId, today);
          
          // Fetch lại sau khi generate
          const newData = await reportService.getOccupancySummary(
            propertyId,
            limit
          );
          setData(newData);
        } catch (genError) {
          console.error("Auto-generate occupancy report failed:", genError);
          setData([]);
        }
      } else {
        setData(summaryData);
      }
    } catch (err) {
      console.error("Error fetching occupancy report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!propertyId) {
      setLoading(false);
      return;
    }

    fetchData();
  }, [propertyId, limit, autoGenerate]);

  // 🔥 REALTIME SUBSCRIPTION - Tự động refresh khi có thay đổi
  useEffect(() => {
    if (!propertyId) return;

    let refetchTimeout;

    // Debounced refetch để tránh nhiều lần fetch liên tiếp
    const debouncedRefetch = () => {
      clearTimeout(refetchTimeout);
      refetchTimeout = setTimeout(async () => {
        // Tự động regenerate báo cáo khi có thay đổi
        try {
          const today = new Date().toISOString().split("T")[0];
          await reportService.generateOccupancyReport(propertyId, today);
          
          // Fetch lại sau khi regenerate
          const updatedData = await reportService.getOccupancySummary(
            propertyId,
            limit
          );
          setData(updatedData);
        } catch (error) {
          console.error("Auto-regenerate occupancy report failed:", error);
          // Nếu regenerate fail, chỉ refresh data hiện có
          fetchData();
        }
      }, 2000); // Đợi 2 giây để tránh regenerate quá nhiều lần
    };

    console.log("🔔 Setting up realtime subscription for occupancy report");

    const channel = supabase
      .channel(`occupancy-report-${propertyId}`)
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "rooms",
        },
        (payload) => {
          console.log("🔔 REALTIME: Room created, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "rooms",
        },
        (payload) => {
          console.log("🔔 REALTIME: Room updated, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "contracts",
        },
        (payload) => {
          console.log("🔔 REALTIME: Contract created, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "contracts",
        },
        (payload) => {
          console.log("🔔 REALTIME: Contract updated, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "tenants",
        },
        (payload) => {
          console.log("🔔 REALTIME: Tenant created, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "tenants",
        },
        (payload) => {
          console.log("🔔 REALTIME: Tenant updated, refreshing occupancy report");
          debouncedRefetch();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "occupancy_summary",
          filter: `property_id=eq.${propertyId}`,
        },
        (payload) => {
          console.log("🔔 REALTIME: New occupancy summary created");
          // Chỉ refresh data, không regenerate
          fetchData();
        }
      )
      .on(
        "postgres_changes",
        {
          event: "UPDATE",
          schema: "public",
          table: "occupancy_summary",
          filter: `property_id=eq.${propertyId}`,
        },
        (payload) => {
          console.log("🔔 REALTIME: Occupancy summary updated");
          // Chỉ refresh data, không regenerate
          fetchData();
        }
      )
      .subscribe((status) => {
        if (status === "SUBSCRIBED") {
          console.log("✅ Occupancy report realtime connected");
        } else if (status === "CHANNEL_ERROR") {
          console.error("❌ Occupancy report realtime error");
        }
      });

    // Cleanup subscription on unmount
    return () => {
      console.log("🔴 Cleaning up occupancy report realtime subscription");
      clearTimeout(refetchTimeout);
      supabase.removeChannel(channel);
    };
  }, [propertyId]);

  const generateReport = async (reportDate = null) => {
    try {
      setLoading(true);
      setError(null);

      await reportService.generateOccupancyReport(propertyId, reportDate);

      // Refresh data after generation
      const updatedData = await reportService.getOccupancySummary(
        propertyId,
        limit
      );
      setData(updatedData);

      return updatedData;
    } catch (err) {
      console.error("Error generating occupancy report:", err);
      setError(err.message);
      throw err;
    } finally {
      setLoading(false);
    }
  };

  const refresh = async () => {
    try {
      setLoading(true);
      const updatedData = await reportService.getOccupancySummary(
        propertyId,
        limit
      );
      setData(updatedData);
    } catch (err) {
      console.error("Error refreshing occupancy report:", err);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return {
    data,
    loading,
    error,
    generateReport,
    refresh,
  };
};
